A set of updates

diff --git a/db_backup_download b/db_backup_download
--- a/db_backup_download
+++ b/db_backup_download
@@ -25,12 +25,16 @@ if [[ -z "$RAILS_ENV" ]]; then
 fi
 
 if [ "$RAILS_ENV" != "production" ]; then
-  if [[ -f .env ]]; then
+  if [[ -f ${ROOT_DIR}/.env ]]; then
     . ${ROOT_DIR}/.env
   fi
 
-  if [[ -f .env.${RAILS_ENV} ]]; then
+  if [[ -f ${ROOT_DIR}/.env.${RAILS_ENV} ]]; then
     . ${ROOT_DIR}/.env.${RAILS_ENV}
+  fi
+
+  if [[ -f ${ROOT_DIR}/.env.db_tools ]]; then
+    . ${ROOT_DIR}/.env.db_tools
   fi
 fi
 
@@ -45,11 +49,11 @@ do
 
   case $key in
     -dd|--dumps-dir)
-      DUMPS_DIR=$2
+      DB_BACKUP_DUMPS_DIR=$2
       shift 2
       ;;
     -dd=*|--dumps-dir=*)
-      DUMPS_DIR="${1#*=}"
+      DB_BACKUP_DUMPS_DIR="${1#*=}"
       shift 1
       ;;
 
@@ -87,27 +91,28 @@ do
 done
 
 if [[ ! -z "$LOCAL_FILE" ]]; then
-  DUMPS_DIR=$(dirname $LOCAL_FILE)
+  DB_BACKUP_DUMPS_DIR=$(dirname $LOCAL_FILE)
 fi
 
-if [[ -z "$DUMPS_DIR" ]]; then
-  DUMPS_DIR=$TMP_DIR/dumps
+if [[ -z "$DB_BACKUP_DUMPS_DIR" ]]; then
+  DB_BACKUP_DUMPS_DIR=$TMP_DIR/dumps
 fi
 
 
 if [[ ( -z "$REMOTE_FILE" ) && ( ! -z "$REMOTE_SIGNED_URL" ) ]]; then
-  REMOTE_FILE=$(db_ls_backups | grep -v next | tail -n 1 | awk '{ print $1; }')
+  echo "Either --remote-file or --signed-url param required" >&2
+  exit 1
 fi
 
 if [[ -z "$LOCAL_FILE" ]]; then
   if [[ ! -z "$REMOTE_SIGNED_URL" ]]; then
-    LOCAL_FILE=$DUMPS_DIR/$(basename $REMOTE_SIGNED_URL | cut -d? -f1)
+    LOCAL_FILE=$DB_BACKUP_DUMPS_DIR/$(basename $REMOTE_SIGNED_URL | cut -d? -f1)
   else
-    LOCAL_FILE=$DUMPS_DIR/$(basename $REMOTE_FILE)
+    LOCAL_FILE=$DB_BACKUP_DUMPS_DIR/$(basename $REMOTE_FILE)
   fi
 fi
 
-mkdir -p $DUMPS_DIR
+mkdir -p $DB_BACKUP_DUMPS_DIR
 
 if [[ -z $REMOTE_SIGNED_URL ]]; then
   S3_FILE_PATH=s3://$DB_BACKUP_TARGET_BUCKET/$REMOTE_FILE
