Moved shared configuration db_backup_setup

diff --git a/db_backup_download b/db_backup_download
--- a/db_backup_download
+++ b/db_backup_download
@@ -1,48 +1,11 @@
 #!/bin/bash
 
-set -e
-
-# Configuration
-# following configuration parameters required:
-# DB_BACKUP_AWS_ACCESS_KEY_ID=
-# DB_BACKUP_AWS_SECRET_ACCESS_KEY=
-# DB_BACKUP_AWS_DEFAULT_REGION=
-# DB_BACKUP_TARGET_BUCKET=
-# DB_BACKUP_ROOT=
-# DB_BACKUP_BASE_NAME=
-
-ROOT_DIR="$( git rev-parse --show-toplevel 2>/dev/null || echo '')"
-
-if [[ -z $ROOT_DIR ]]; then
-  TMP_DIR=$ROOT_DIR/tmp
-else
-  TMP_DIR=/tmp
-fi
+## Peform setup
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+. ${SCRIPT_DIR}/db_backup_setup
 
 
-if [[ -z "$RAILS_ENV" ]]; then
-  RAILS_ENV=development
-fi
-
-if [ "$RAILS_ENV" != "production" ]; then
-  if [[ -f ${ROOT_DIR}/.env ]]; then
-    . ${ROOT_DIR}/.env
-  fi
-
-  if [[ -f ${ROOT_DIR}/.env.${RAILS_ENV} ]]; then
-    . ${ROOT_DIR}/.env.${RAILS_ENV}
-  fi
-
-  if [[ -f ${ROOT_DIR}/.env.db_tools ]]; then
-    . ${ROOT_DIR}/.env.db_tools
-  fi
-fi
-
-export AWS_ACCESS_KEY_ID=${DB_BACKUP_AWS_ACCESS_KEY_ID}
-export AWS_SECRET_ACCESS_KEY=${DB_BACKUP_AWS_SECRET_ACCESS_KEY}
-export AWS_DEFAULT_REGION=${DB_BACKUP_AWS_DEFAULT_REGION}
-
-
+## Process params
 while [[ $# -gt 0 ]]
 do
   key="$1"
@@ -117,6 +80,7 @@ mkdir -p $DB_BACKUP_DUMPS_DIR
 if [[ -z $REMOTE_SIGNED_URL ]]; then
   S3_FILE_PATH=s3://$DB_BACKUP_TARGET_BUCKET/$REMOTE_FILE
 
+  echo aws s3 cp "$S3_FILE_PATH" "$LOCAL_FILE" --only-show-errors >&2
   aws s3 cp "$S3_FILE_PATH" "$LOCAL_FILE" --only-show-errors
 else
   wget "$REMOTE_SIGNED_URL" -O "$LOCAL_FILE"
diff --git a/db_backup_to_s3 b/db_backup_to_s3
--- a/db_backup_to_s3
+++ b/db_backup_to_s3
@@ -2,6 +2,13 @@
 
 set -e
 
+trap 'on_error $LINENO' ERR
+
+on_error() {
+  LINE=$1
+  printf "Error at LINE NUMBER: $LINE"
+}
+
 # Configuration
 # following configuration parameters required:
 # DB_BACKUP_AWS_ACCESS_KEY_ID=
@@ -11,10 +18,10 @@ set -e
 # DB_BACKUP_ROOT=
 # DB_BACKUP_BASE_NAME=
 
-ROOT_DIR="$( git rev-parse --show-toplevel 2>/dev/null || echo '')"
+BASE_DIR="$( git rev-parse --show-toplevel 2>/dev/null || echo '')"
 
-if [[ -z $ROOT_DIR ]]; then
-  TMP_DIR=$ROOT_DIR/tmp
+if [[ -z $BASE_DIR ]]; then
+  TMP_DIR=$BASE_DIR/tmp
 else
   TMP_DIR=/tmp
 fi
@@ -24,16 +31,16 @@ if [[ -z "$RAILS_ENV" ]]; then
 fi
 
 if [ "$RAILS_ENV" != "production" ]; then
-  if [[ -f ${ROOT_DIR}/.env ]]; then
-    . ${ROOT_DIR}/.env
+  if [[ -f ${BASE_DIR}/.env ]]; then
+    . ${BASE_DIR}/.env
   fi
 
-  if [[ -f ${ROOT_DIR}/.env.${RAILS_ENV} ]]; then
-    . ${ROOT_DIR}/.env.${RAILS_ENV}
+  if [[ -f ${BASE_DIR}/.env.${RAILS_ENV} ]]; then
+    . ${BASE_DIR}/.env.${RAILS_ENV}
   fi
 
-  if [[ -f ${ROOT_DIR}/.env.db_tools ]]; then
-    . ${ROOT_DIR}/.env.db_tools
+  if [[ -f ${BASE_DIR}/.env.db_tools ]]; then
+    . ${BASE_DIR}/.env.db_tools
   fi
 fi
 
